name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi thanks for submitting an issue DM me on discord or twitter if you can so I can take a look and determine priorities.'' first issue'
        pr-message: 'If you make something cool push it and i'll take a look on whether to merge it. if you break it then rm -rf and pull again.'' first pr'
